// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NOTIFICATIONSAPP.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NotificationsApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NOTIFICATIONSAPP.Models.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Filename")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<JsonDocument>("Meta")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uuid");

                    b.Property<long?>("Size")
                        .HasColumnType("bigint");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NotificationId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("NOTIFICATIONSAPP.Models.DeliveryAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AttemptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("HttpStatus")
                        .HasColumnType("integer");

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TargetUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AttemptedAt");

                    b.HasIndex("NotificationId");

                    b.ToTable("DeliveryAttempts");
                });

            modelBuilder.Entity("NOTIFICATIONSAPP.Models.Integration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalAccountId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<JsonDocument>("Settings")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrgId");

                    b.HasIndex("Provider", "ExternalAccountId");

                    b.ToTable("Integrations");
                });

            modelBuilder.Entity("NOTIFICATIONSAPP.Models.IntegrationChannel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<JsonDocument>("Config")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalChannelId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("IntegrationId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("IntegrationId", "ExternalChannelId")
                        .IsUnique();

                    b.ToTable("IntegrationChannels");
                });

            modelBuilder.Entity("NOTIFICATIONSAPP.Models.IntegrationCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CredentialType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IntegrationId")
                        .HasColumnType("uuid");

                    b.Property<JsonDocument>("Meta")
                        .HasColumnType("jsonb");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IntegrationId");

                    b.ToTable("IntegrationCredentials");
                });

            modelBuilder.Entity("NOTIFICATIONSAPP.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<string>("ExternalChannelId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ExternalUserId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("IntegrationChannelId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IntegrationId")
                        .HasColumnType("uuid");

                    b.Property<JsonDocument>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ProviderEventId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("new");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalChannelId");

                    b.HasIndex("ExternalUserId");

                    b.HasIndex("IntegrationChannelId");

                    b.HasIndex("IntegrationId");

                    b.HasIndex("ProviderEventId");

                    b.HasIndex("ReceivedAt");

                    b.HasIndex("Status");

                    b.HasIndex("Provider", "ProviderEventId")
                        .IsUnique()
                        .HasFilter("\"ProviderEventId\" IS NOT NULL");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("NOTIFICATIONSAPP.Models.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("NOTIFICATIONSAPP.Models.OrganizationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("member");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("OrganizationId", "UserId")
                        .IsUnique();

                    b.ToTable("OrganizationUsers");
                });

            modelBuilder.Entity("NOTIFICATIONSAPP.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NOTIFICATIONSAPP.Models.UserChannel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("IntegrationChannelId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsMember")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ReceiveNotifications")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IntegrationChannelId");

                    b.HasIndex("UserId", "IntegrationChannelId")
                        .IsUnique();

                    b.ToTable("UserChannels");
                });

            modelBuilder.Entity("NOTIFICATIONSAPP.Models.UserIntegration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalUserId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ExternalUsername")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("IntegrationId")
                        .HasColumnType("uuid");

                    b.Property<bool>("ReceiveNotifications")
                        .HasColumnType("boolean");

                    b.Property<JsonDocument>("Settings")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExternalUserId");

                    b.HasIndex("IntegrationId");

                    b.HasIndex("UserId", "IntegrationId")
                        .IsUnique();

                    b.ToTable("UserIntegrations");
                });

            modelBuilder.Entity("NOTIFICATIONSAPP.Models.UserNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("NotificationId");

                    b.HasIndex("UserId", "IsRead");

                    b.HasIndex("UserId", "NotificationId")
                        .IsUnique();

                    b.ToTable("UserNotifications");
                });

            modelBuilder.Entity("NOTIFICATIONSAPP.Models.Attachment", b =>
                {
                    b.HasOne("NOTIFICATIONSAPP.Models.Notification", "Notification")
                        .WithMany("Attachments")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notification");
                });

            modelBuilder.Entity("NOTIFICATIONSAPP.Models.DeliveryAttempt", b =>
                {
                    b.HasOne("NOTIFICATIONSAPP.Models.Notification", "Notification")
                        .WithMany("DeliveryAttempts")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notification");
                });

            modelBuilder.Entity("NOTIFICATIONSAPP.Models.Integration", b =>
                {
                    b.HasOne("NOTIFICATIONSAPP.Models.Organization", "Organization")
                        .WithMany("Integrations")
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("NOTIFICATIONSAPP.Models.IntegrationChannel", b =>
                {
                    b.HasOne("NOTIFICATIONSAPP.Models.Integration", "Integration")
                        .WithMany("Channels")
                        .HasForeignKey("IntegrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Integration");
                });

            modelBuilder.Entity("NOTIFICATIONSAPP.Models.IntegrationCredential", b =>
                {
                    b.HasOne("NOTIFICATIONSAPP.Models.Integration", "Integration")
                        .WithMany("Credentials")
                        .HasForeignKey("IntegrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Integration");
                });

            modelBuilder.Entity("NOTIFICATIONSAPP.Models.Notification", b =>
                {
                    b.HasOne("NOTIFICATIONSAPP.Models.IntegrationChannel", "IntegrationChannel")
                        .WithMany("Notifications")
                        .HasForeignKey("IntegrationChannelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NOTIFICATIONSAPP.Models.Integration", "Integration")
                        .WithMany("Notifications")
                        .HasForeignKey("IntegrationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Integration");

                    b.Navigation("IntegrationChannel");
                });

            modelBuilder.Entity("NOTIFICATIONSAPP.Models.OrganizationUser", b =>
                {
                    b.HasOne("NOTIFICATIONSAPP.Models.Organization", "Organization")
                        .WithMany("OrganizationUsers")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NOTIFICATIONSAPP.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NOTIFICATIONSAPP.Models.UserChannel", b =>
                {
                    b.HasOne("NOTIFICATIONSAPP.Models.IntegrationChannel", "IntegrationChannel")
                        .WithMany("UserChannels")
                        .HasForeignKey("IntegrationChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NOTIFICATIONSAPP.Models.User", "User")
                        .WithMany("UserChannels")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IntegrationChannel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NOTIFICATIONSAPP.Models.UserIntegration", b =>
                {
                    b.HasOne("NOTIFICATIONSAPP.Models.Integration", "Integration")
                        .WithMany("UserIntegrations")
                        .HasForeignKey("IntegrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NOTIFICATIONSAPP.Models.User", "User")
                        .WithMany("UserIntegrations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Integration");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NOTIFICATIONSAPP.Models.UserNotification", b =>
                {
                    b.HasOne("NOTIFICATIONSAPP.Models.Notification", "Notification")
                        .WithMany("UserNotifications")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NOTIFICATIONSAPP.Models.User", "User")
                        .WithMany("UserNotifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notification");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NOTIFICATIONSAPP.Models.Integration", b =>
                {
                    b.Navigation("Channels");

                    b.Navigation("Credentials");

                    b.Navigation("Notifications");

                    b.Navigation("UserIntegrations");
                });

            modelBuilder.Entity("NOTIFICATIONSAPP.Models.IntegrationChannel", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("UserChannels");
                });

            modelBuilder.Entity("NOTIFICATIONSAPP.Models.Notification", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("DeliveryAttempts");

                    b.Navigation("UserNotifications");
                });

            modelBuilder.Entity("NOTIFICATIONSAPP.Models.Organization", b =>
                {
                    b.Navigation("Integrations");

                    b.Navigation("OrganizationUsers");
                });

            modelBuilder.Entity("NOTIFICATIONSAPP.Models.User", b =>
                {
                    b.Navigation("UserChannels");

                    b.Navigation("UserIntegrations");

                    b.Navigation("UserNotifications");
                });
#pragma warning restore 612, 618
        }
    }
}
